Updated the pbin command.

diff --git a/util/pbin b/util/pbin
--- a/util/pbin
+++ b/util/pbin
@@ -13,9 +13,7 @@ if [ -t 0 ]; then
 fi
 
 if [ ! -t 0 ]; then
-	echo "catting -"
 	content=$(cat -)
-	echo "- catted"
 	name="$1"
 else
 	content=$(cat $1)
@@ -27,5 +25,6 @@ pasteId=$(curl "$url" -s -F "name=$name" -F "content=$content")
 if [ $? -eq 0 ]; then
 	echo "Your paste should now be at http://pbin.in/$pasteId"
 else
-	echo "There was an error. The file you provided may be too big."
+	echo "An error occurred." 1>&2
+	exit 1
 fi
